from __future__ import annotations

DETECTION_SCORE_THRESHOLD = 0.80

HEALTH_B_THRESHOLD = 0.70
HEALTH_IMAGE_SIZE = 224

CROP_EXPAND_RATIO = 0.08
MIN_CROP_WIDTH = 20
MIN_CROP_HEIGHT = 20

MATURITY_MIN_CROP_WIDTH = 20
MATURITY_MIN_CROP_HEIGHT = 20
MATURITY_MIN_DET_SCORE = 0.80

MIN_FRAMES_BETWEEN_CAPTURES = 18
MAX_FRAMES_WITHOUT_CAPTURE = 45
CENTER_CROP_RATIO = 0.60
ORB_MIN_MATCH_COUNT = 35
HSV_HIST_DIFF_THRESHOLD = 0.38
USE_HISTOGRAM_VALIDATION = True