"""Domain entity: ExportPackage.

Represents a ZIP export package generated by the system.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class ExportPackage:
    """A ZIP export package containing structured data and images."""

    created_by_user_id: int
    scope: str
    id: Optional[int] = None
    scope_id: Optional[int] = None
    file_path: Optional[str] = None
    file_size_bytes: Optional[int] = None
    status: str = field(default="pending")
    error_message: Optional[str] = None
    records_count: int = field(default=0)
    images_count: int = field(default=0)
    created_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    manifest_json: Optional[str] = None

    def __post_init__(self) -> None:
        if self.created_by_user_id <= 0:
            raise ValueError("created_by_user_id must be positive")
        valid_scopes = ("full", "greenhouse", "module", "monitoring")
        if self.scope not in valid_scopes:
            raise ValueError(f"scope must be one of {valid_scopes}, got '{self.scope}'")
        valid_statuses = ("pending", "generating", "completed", "error")
        if self.status not in valid_statuses:
            raise ValueError(f"status must be one of {valid_statuses}, got '{self.status}'")
        if self.scope_id is not None and self.scope_id <= 0:
            raise ValueError("scope_id must be positive")
        if self.file_size_bytes is not None and self.file_size_bytes < 0:
            raise ValueError("file_size_bytes must be non-negative")
        if self.records_count < 0:
            raise ValueError("records_count must be non-negative")
        if self.images_count < 0:
            raise ValueError("images_count must be non-negative")
        if self.id is not None and self.id <= 0:
            raise ValueError("id must be positive")
